import * as THREE from 'three'

/**
 * Weapon registry.
 *
 * Every entry is a real spatial behaviour, not a damage number. `kind` selects
 * the delivery mechanism (how it travels through 3D space), the rest describes
 * what it does to the damage field when it arrives.
 *
 * dps/impulse are per-second for beams, per-shot for kinetics.
 */

export const CATEGORIES = ['LASER', 'KINETIC', 'ENERGY', 'THERMAL', 'GRAVITY', 'ORBITAL', 'COSMIC']

export const WEAPONS = {
  'precision-laser': {
    id: 'precision-laser',
    name: 'Precision Laser',
    category: 'LASER',
    kind: 'beam',
    desc: 'Hair-fine coherent beam. Surgical excavation, negligible splash.',
    color: new THREE.Color('#6fd7ff'),
    coreColor: new THREE.Color('#eafcff'),
    beamWidth: 0.006,
    radius: 0.012,          // angular radius on the surface (radians)
    depth: 1.9,             // excavation rate /sec
    heat: 2.2,
    scorch: 1.1,
    penetration: 0.55,
    falloff: 2.6,
    jagged: 0.15,
    sparks: 14,
    debrisRate: 5,
    debrisSpeed: 0.35,
    shake: 0.02,
    disturb: 0.0,
    lethality: 0.0000008,
    flicker: 26,
  },

  'thermal-beam': {
    id: 'thermal-beam',
    name: 'Thermal Beam',
    category: 'THERMAL',
    kind: 'beam',
    desc: 'Wide infrared column. Melts crust into glowing slag rather than cutting it.',
    color: new THREE.Color('#ff7a2f'),
    coreColor: new THREE.Color('#ffe9c4'),
    beamWidth: 0.028,
    radius: 0.055,
    depth: 0.85,
    heat: 5.0,
    scorch: 3.4,
    penetration: 0.05,
    falloff: 1.5,
    jagged: 0.45,
    sparks: 26,
    debrisRate: 9,
    debrisSpeed: 0.22,
    shake: 0.04,
    disturb: 0.06,
    lethality: 0.0000045,
    flicker: 9,
  },

  'planetary-cutter': {
    id: 'planetary-cutter',
    name: 'Planetary Cutter',
    category: 'LASER',
    kind: 'beam',
    desc: 'Sustained fissure beam. Drag across the surface to open a continental scar.',
    color: new THREE.Color('#c66bff'),
    coreColor: new THREE.Color('#fbeaff'),
    beamWidth: 0.014,
    radius: 0.026,
    depth: 3.1,
    heat: 3.0,
    scorch: 2.0,
    penetration: 1.15,
    falloff: 3.4,
    jagged: 0.22,
    sparks: 20,
    debrisRate: 14,
    debrisSpeed: 0.5,
    shake: 0.06,
    disturb: 0.05,
    lethality: 0.000006,
    flicker: 16,
  },

  'cataclysm-beam': {
    id: 'cataclysm-beam',
    name: 'Cataclysm Beam',
    category: 'COSMIC',
    kind: 'beam',
    desc: 'Mantle-piercing discharge. Breaches the crust and exposes the core.',
    color: new THREE.Color('#ff3b6b'),
    coreColor: new THREE.Color('#fff0f4'),
    beamWidth: 0.075,
    radius: 0.10,
    depth: 5.5,
    heat: 6.0,
    scorch: 3.0,
    penetration: 2.6,
    falloff: 2.0,
    jagged: 0.3,
    sparks: 44,
    debrisRate: 30,
    debrisSpeed: 0.85,
    shake: 0.16,
    disturb: 0.22,
    lethality: 0.00004,
    flicker: 5,
    charge: 1.1,            // seconds of spool-up before it fires
  },

  'kinetic-slug': {
    id: 'kinetic-slug',
    name: 'Kinetic Slug',
    category: 'KINETIC',
    kind: 'projectile',
    desc: 'Tungsten rod at orbital velocity. No explosive — pure momentum.',
    color: new THREE.Color('#ffd27a'),
    coreColor: new THREE.Color('#fff6e0'),
    speed: 2.6,
    projectileSize: 0.012,
    radius: 0.05,
    depth: 4.5,
    heat: 2.4,
    scorch: 1.6,
    penetration: 0.9,
    falloff: 1.7,
    jagged: 0.5,
    blast: 0.16,
    sparks: 90,
    debrisBurst: 40,
    debrisSpeed: 0.7,
    shake: 0.22,
    disturb: 0.10,
    lethality: 0.004,
    cooldown: 0.55,
  },

  'meteor-strike': {
    id: 'meteor-strike',
    name: 'Meteor Strike',
    category: 'KINETIC',
    kind: 'projectile',
    desc: 'Redirected asteroid. Arrives burning, leaves a basin.',
    color: new THREE.Color('#ff8a3d'),
    coreColor: new THREE.Color('#fff1d0'),
    speed: 1.35,
    projectileSize: 0.05,
    trail: true,
    radius: 0.14,
    depth: 7.0,
    heat: 5.5,
    scorch: 4.0,
    penetration: 1.4,
    falloff: 1.4,
    jagged: 0.6,
    blast: 0.42,
    sparks: 180,
    debrisBurst: 120,
    debrisSpeed: 1.05,
    shake: 0.5,
    disturb: 0.34,
    atmoStrip: 0.03,
    lethality: 0.09,
    cooldown: 1.6,
  },

  'plasma-lance': {
    id: 'plasma-lance',
    name: 'Plasma Lance',
    category: 'ENERGY',
    kind: 'projectile',
    desc: 'Magnetically bottled plasma bolt. Detonates on contact.',
    color: new THREE.Color('#54ffd0'),
    coreColor: new THREE.Color('#e9fffa'),
    speed: 2.0,
    projectileSize: 0.026,
    radius: 0.085,
    depth: 3.2,
    heat: 7.0,
    scorch: 2.2,
    penetration: 0.7,
    falloff: 1.9,
    jagged: 0.35,
    blast: 0.3,
    sparks: 130,
    debrisBurst: 70,
    debrisSpeed: 0.9,
    shake: 0.3,
    disturb: 0.18,
    lethality: 0.02,
    cooldown: 0.9,
  },

  'gravity-well': {
    id: 'gravity-well',
    name: 'Gravity Well',
    category: 'GRAVITY',
    kind: 'field',
    desc: 'Localised singularity. Lifts crust and debris off the surface.',
    color: new THREE.Color('#8b7dff'),
    coreColor: new THREE.Color('#1a1030'),
    radius: 0.13,
    depth: 1.4,
    heat: 0.2,
    scorch: 0.4,
    penetration: 0.3,
    falloff: 1.2,
    jagged: 0.7,
    pull: 2.4,
    duration: 3.2,
    sparks: 40,
    debrisRate: 22,
    debrisSpeed: -0.5,     // negative = inward
    shake: 0.08,
    disturb: 0.12,
    lethality: 0.00002,
  },
}

export const WEAPON_LIST = Object.values(WEAPONS)
export const weaponFor = (id) => WEAPONS[id] || WEAPONS['precision-laser']
